# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('main_ticket', models.IntegerField()),
                ('product', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date_update', models.DateTimeField()),
                ('date_closed', models.DateTimeField()),
            ],
        ),
    ]
